version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backendapp
    ports:
      - "5000:5000"
    command: npm run dev
    networks:
      - myappnet
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontendapp
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - myappnet
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

networks:
  myappnet:
    driver: bridge